apiVersion: v1
kind: ConfigMap
metadata:
  name: amazonq-mcp-config
  namespace: ${{values.namespace}}
data:
  mcp.json: |
    {
      "version": "1.0",
      "mcps": [
        {
          "name": "bedrock-kb-mcp",
          "endpoint": "http://bedrock-kb-mcp-service.${{values.namespace}}.svc.cluster.local:8080",
          "auth": {
            "type": "oauth2",
            "oauth2": {
              "clientId": "${{values.keycloakClientId}}",
              "authorizationEndpoint": "https://${{values.keycloakUrl}}/realms/${{values.keycloakRealm}}/protocol/openid-connect/auth",
              "tokenEndpoint": "https://${{values.keycloakUrl}}/realms/${{values.keycloakRealm}}/protocol/openid-connect/token"
            }
          }
        }
      ]
    }