apiVersion: v1
kind: Secret
metadata:
  name: bedrock-kb-mcp-keycloak
  namespace: ${{values.namespace}}
type: Opaque
stringData:
  KEYCLOAK_URL: "${{values.keycloakUrl}}"
  KEYCLOAK_REALM: "${{values.keycloakRealm}}"
  KEYCLOAK_CLIENT_ID: "${{values.keycloakClientId}}"
  KEYCLOAK_CLIENT_SECRET: "${{values.keycloakClientSecret}}"