apiVersion: v1
kind: Service
metadata:
  name: bedrock-kb-mcp-service
  namespace: ${{values.namespace}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: bedrock-kb-mcp
    app.kubernetes.io/name: bedrock-kb-mcp
    app.kubernetes.io/part-of: mcp
spec:
  selector:
    app: bedrock-kb-mcp
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer