apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.appname}}
  description: Deploy CI/CD Pipeline for ${{ values.appname }}
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.appname}}'
    argocd/app-selector: 'entity-id=${{values.appname}}'
    argo-workflows.cnoe.io/cluster-name: local
    argo-workflows.cnoe.io/namespace: team-${{values.appname}}
    argo-workflows.cnoe.io/label-selector: 'entity-id=${{values.appname}}'
  links:
    - url: https://${{values.hostname}}/gitea?repo=${{values.appname}}-cicd
      title: Repo URL
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: ${{values.appname | dump}}

