apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-mgmt
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  source:
    repoURL: ${GITHUB_URL}
    targetRevision: HEAD
    path: deployment/addons/kubevela
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vela-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
