apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-dev
  namespace: argocd
spec:
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.0
      helm:
        releaseName: ingress-nginx-dev
        parameters:
          - name: controller.config.hsts
            value: 'false'
          - name: controller.service.type
            value: LoadBalancer
          - name: controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-name"
            value: "modernengg-dev"
          - name: controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"
            value: "external"
          - name: controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"
            value: "internet-facing"
          - name: controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type"
            value: "ip"
          - name: controller.service.loadbalancerClass
            value: "service.k8s.aws/nlb"
          - name: controller.service.targetPorts.https
            value: 'https'
  destination:
    name: 'dev-cluster'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
