version: 0.2
phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common apt-transport-https ca-certificates curl jq
      # Install aws-cli
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install
      # install terraform
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform
      # Install kubectl
      - sudo apt-get update
      - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      - sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
      - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
      - sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list
      - sudo apt-get update
      - sudo apt-get install -y kubectl
      # Get S3 Bucket
      - export TF_VAR_state_s3_bucket=$(aws s3 ls | grep eks-accelerator | awk '{print $3}')
      # Get DynamoDB Table
      - export TF_VAR_state_ddb_lock_table=$(aws dynamodb list-tables | jq -r '.TableNames[] | select("eks-accelerator-tf-lock")')
      # Get vpc
      - export TF_VAR_vpc_id=$(aws ec2 describe-vpcs --filters Name=tag:Name,Values="modern-engineering" --query 'Vpcs[*].{VpcId:VpcId,Name:Tags[?Key==`Name`].Value|[0]}' --output text | awk '{print $2}')
      # Get vpc private subnets
      - export TF_VAR_vpc_private_subnets=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$TF_VAR_vpc_id" "Name=tag:Name,Values=*private*" --query "Subnets[*].SubnetId" --output json)
      # Get AMP ID
      - export TF_VAR_managed_prometheus_workspace_id=$(aws amp list-workspaces | jq -r '.workspaces[] | select(.alias=="aws-observability-accelerator-multicluster") | .workspaceId')
      # Get AMG ID
      - export TF_VAR_managed_grafana_workspace_id=$(aws grafana list-workspaces | jq -r '.workspaces[] | select(.name=="aws-observability-accelerator") | .id')
      # Get AMG Key
      - export PARAMETER_PATH=$(aws ssm get-parameters-by-path --path "/terraform-accelerator/grafana-api-key/" --recursive --with-decryption --query "Parameters[].Name" --output text)
      - export AMG_API_KEY=$(aws ssm get-parameter --name $PARAMETER_PATH --with-decryption --query "Parameter.Value" --output text | jq -r '.["GF_SECURITY_ADMIN_APIKEY"]')
      # Clone Gitea repo
      - export GITEA_REPO=$GITEA_URL/giteaAdmin/terraform-eks.git
      - echo "Cloning Gitea repository..."
      - git -c http.sslVerify=false clone $GITEA_REPO
      - cd terraform-eks
      - chmod +x ./create-cluster.sh
      - ./create-cluster.sh
