version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - cd ./applications/rust/
      - docker build -t $ECR_REGISTRY/app/rust-microservice:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $ECR_REGISTRY/app/rust-microservice:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd integration
      - docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION

  integration:
    commands:
      - cd ./application/rust/
      - cargo test # @vshardul write some tests brother. Unit tests are usually quite nice
